source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'MGDS_Swift' do
    # Swift
    pod 'Alamofire'        # 网络请求  #, '~> 4.9.1'
    pod 'Just'             #, '~> 0.8.0'
    pod 'Kingfisher'           # 图片加载 #, '~> 4.10.1'
    pod 'SnapKit'             # 约束布局 #, '~> 4.2.0'

    pod 'IQKeyboardManagerSwift'  # 键盘扩展 #, '6.5.10'
    pod 'Validator'           # 输入正确校验 , '~> 3.2.1'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'   # 处理JSON数据 , '~> 5.0.1'
 
    # OC
    pod 'MJRefresh'         # 刷新数据 , '~> 3.7.5'
    pod 'MBProgressHUD'   # 蒙版提示 , '~> 1.2.0'
    pod 'ZFPlayer'            # 视频播放 , '~> 4.0.3'
  
#    // Mob产品公共库
    pod 'MOBFoundation'
#    pod 'MOBFoundation_IDFA'  # ,'~> 3.2.36  IDFA 3.0.5'
#    // SMSSDK必须
    pod 'SMSSDK'              #'~> 3.0.1'
    
    
    pod 'pop'            #',~> 1.0.12'
    
    
    pod 'NAKPlaybackIndicatorView'       # ,'~> 0.1.1'
    pod 'FMDB'                 # 数据存储 # ,'~> 2.7.5'
    
  
end
