source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'MGDS_Swift' do
    # Swift
    pod 'Alamofire', '~> 4.2.0'
    pod 'Kingfisher', '~> 3.2.1'
    pod 'SnapKit', '~> 3.0.2'
    # 键盘扩展
    pod 'IQKeyboardManagerSwift', '4.0.6'
    pod 'Validator', '~> 2.1.1'
 
    # OC
    pod 'MJRefresh', '~> 3.1.12'
    pod 'MBProgressHUD', '~> 0.9.2'
  
#    // Mob产品公共库
    pod 'MOBFoundation_IDFA', '~> 2.2.3'
#    // SMSSDK必须
    pod 'SMSSDK', '~> 2.0.8'
  
end
